// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
/*
module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Overview',
      items: ['overview'],
    },
    {
      type: 'category',
      label: 'Rules & Phases',
      items: [
        'rules/game-phases',
        'rules/scoring',
        'rules/dog-behavior',
        'rules/handler-controls',
      ],
    },
    {
      type: 'category',
      label: 'Obstacles',
      items: [
        'obstacles/index',
        'obstacles/a-frame',
        'obstacles/chute',
        'obstacles/weave-poles',
      ],
    },
    {
      type: 'category',
      label: 'Tile System',
      items: [
        'tiles/hex-basics',
        'tiles/field-sizes',
        'tiles/spacing-rules',
      ],
    },
    {
      type: 'category',
      label: 'Legacy & Notes',
      items: ['legacy/2016-obsolete-objects'],
    },
  ],
};
*/



/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
